### ISSUE TITLE
Character sheet won't load a custom background.

### ISSUE THREAD

**Issue by Vehdrehl** [Azmoria/dndbeyonddark#1]
When setting a custom background via Stylus it doesn't show up. The background remains black.
![download](https://user-images.githubusercontent.com/26274729/116800063-450a1280-ab30-11eb-9a9e-3aa87fb00110.png)
![download (1)](https://user-images.githubusercontent.com/26274729/116800066-476c6c80-ab30-11eb-9d1b-89c07f6fa4a9.png)

**Comment by Azmoria** [comment]
Include url() with the brackets around the url eg. url(http://www.imgur.com/example.jpg). I will add some clarification to the name of the field.

**Comment by Vehdrehl** [comment]
Oh, I'm a big dumb. It's quite clear now that you mention it.
