### ISSUE TITLE
Rolls of other players does not get stylized.

### ISSUE THREAD

**Issue by SparJar** [Azmoria/dndbeyonddark#2]
Hello, 
   I am absolutely loving this, but the only issue I have is that other player rolls do not get the background stylized and it stays white. I cannot see where to change it myself.  If it is there and I am blind then I apologize.

**Comment by Azmoria** [comment]
I just pushed an update that should fix this. The class names they used for the game log are not static so I had to change the way those are targeted.

**Comment by SparJar** [comment]
Awesome! I'll check it out!

**Comment by Azmoria** [comment]
The popup for others rolls when the game log isn't open should now also be fixed. I will keep an eye out to see if these changes affected anything else.

Edit: This has negatively affected other parts of the theme. I have adjusted it with another update and will continue to watch if further changes are needed. As such I will be leaving this open until I am confident it is working.

**Comment by SparJar** [comment]
The campaign I am using DnD Beyond for next meets on Monday so I will know for certain that everything is working then, but I just installed the update and everything looks good currently just clicking through.

**Comment by Azmoria** [comment]
Thanks for checking it out and reporting it to begin with @SparJar. I don't believe the fix has any more unintended side effects and am closing this issue.
