### ISSUE TITLE
Option to replace Highlight Color with default from theme

### ISSUE THREAD

**Issue by MuffinGamedev** [Azmoria/dndbeyonddark#3]
This theme seems to require a highlight color to be selected, which then colors aspects of the character sheet, replacing D&D Beyond's default Theme option that allows you to similarly choose a highlight color for your character sheet. I would like to use the character sheet's built-in theme as the highlight color across all character sheets; is it possible to achieve this effect?

**Comment by Azmoria** [comment]
Hi Muffin,

Are you asking if it can pull the theme color and apply it as the highlight color? Unfortunately this, to my knowledge, is not possible with pure CSS. Dndbeyond does not store the theme color as a global CSS variable. The theme color variable is stored in a meta tag which I believe would require JavaScript to access. 

 document.querySelector("meta[property='theme-color']").getAttribute("content")

Would be the JavaScript to get the color then you would have to set it to a CSS variable. You would set up an event listener for when the user changes it.

This is beyond the scope of what I can do with this theme/extension.


**HOWEVER**

You can create a theme for each character by creating a copy of the theme. 

Scroll down to 
![image](https://user-images.githubusercontent.com/65363489/121752766-df218b00-cade-11eb-95ef-a4e9e91b47e3.png)

Where it says https://www.dndbeyond.com/profile/.*/characters/\\d* - You can delete the other line below by hitting the minus sign.

Put in the specific url for your character as so:

![image](https://user-images.githubusercontent.com/65363489/121752934-40495e80-cadf-11eb-853a-c8f69447c142.png)


and again further down as so:

![image](https://user-images.githubusercontent.com/65363489/121752983-59eaa600-cadf-11eb-8840-3e65ba83e56b.png)

again you can remove the other lines if you wish they are for dice outside the character sheet.

See here for more information on creating a companion style - or if you would like assistance setting this up you can add me on discord at Azmoria#7532

https://github.com/openstyles/stylus/wiki/Writing-styles#making-a-companion-style

**Comment by MuffinGamedev** [comment]
Thanks for the quick response; I'll try that :)
