### ISSUE TITLE
Can't see the dice

### ISSUE THREAD

**Issue by JaspherMilesPillado** [Azmoria/dndbeyonddark#5]
Hey, I was trying to get the dice tray working. The window pops up but I can't see neither the character sheet to customize it nor the dice itself when rolling. I've enabled the flag for chrome as well. Was wondering if you might know anything I might've done wrong?

Thanks in advance!

**Comment by Azmoria** [comment]
Hey

I accepted the friend request on discord. 

It seems to still be working for me. 

Example:
https://youtu.be/ZoFI11crVpk


Not seeing the dice is odd - it's possible it's loading to quickly before the sheet has initialized. The customization should be in the character sheet theme or other theme if trying to use it in DM spaces. (See video)

If you go into the script it self in tampermonkey (or whichever extention you've choosen) 

At the bottom where it says this:
```
setTimeout(async function() {
    childWindow = await diceTray();
    window.childWindow = childWindow;
    window.parent.childWindow = childWindow;
}, 2000);
```


try changing the 2000 to 15000 and if that works (15 seconds after openning the page) it's probably just loading the script to quickly.

eg.
```
setTimeout(async function() {
    childWindow = await diceTray();
    window.childWindow = childWindow;
    window.parent.childWindow = childWindow;
}, 15000);
```

Feel free to msg me on discord if you need more assistance or if that fix works for you. I may implement something that would be better than just a timeout - this was a just a quick job to get something functional at the time.
