### ISSUE TITLE
Dark purple text in Tome of Beasts sourcebook difficult to read

### ISSUE THREAD

**Issue by Polteageist** [Azmoria/dndbeyonddark#8]
The new Tome of Beasts 1 book contains dark purple text in both the passages of the book and embedded monster statblocks that is difficult to read against the black background supplied by this style.
![dark_purple](https://github.com/Azmoria/dndbeyonddark/assets/106500712/0d9115da-486f-4698-8c23-76ea5f8dc866)

**Comment by Azmoria** [comment]
Added it to the font contrast option (default dark mode) and fixed the places where it was overriding the existing font contrast of the style. If you notice anything else let me know - I'll leave this open for a few days at least before closing it.


![image](https://github.com/Azmoria/dndbeyonddark/assets/65363489/b43ad87a-3f48-4d6b-9d70-af586c71abe6)

vs

![image](https://github.com/Azmoria/dndbeyonddark/assets/65363489/63014c88-201e-45af-8ed0-d353bd3d88e8)

**Comment by Polteageist** [comment]
Thank you very much, it's much easier on the eyes now :)
I'll update if I notice anything amiss.
