### ISSUE TITLE
Spell technical details section unaffected by font color

### ISSUE THREAD

**Issue by Laughing-Jackal** [Azmoria/dndbeyonddark#9]
v1.2.485

In the character builder the section that describes the casting time, range, components, duration, and source remain a dark black for all spells and are unaffected by any of the stylus configuration dropdown color options including background color and font color.

Currently unsure what line(s) control this section.

![Screenshot 2024-05-16 12-49-32](https://github.com/Azmoria/dndbeyonddark/assets/16396437/6091aed1-3ff1-484b-8fc3-0528172b2da6)
![Screenshot 2024-05-16 12-49-37](https://github.com/Azmoria/dndbeyonddark/assets/16396437/f14c53c0-e680-4410-bcda-869af3dcf41a)

**Comment by Laughing-Jackal** [comment]
Using inspect it seems that these are the sections that control the aforementioned details, they have somehow become unlinked from the configuration dropdown. 

To clarify, I am using version 1.2.485 of the style and have attempted a reinstall of the style as well as the extension itself to no change.

![Screenshot 2024-05-23 11-25-43](https://github.com/Azmoria/dndbeyonddark/assets/16396437/862bf4c3-5114-43bf-893a-ad8b71104784)
![Screenshot 2024-05-23 11-27-57](https://github.com/Azmoria/dndbeyonddark/assets/16396437/f353b413-d679-4a4f-a4aa-3177085af899)

**Comment by Azmoria** [comment]
Ah thanks for the report sorry I didn't get to it sooner. It seems if you only have the normal dark mode and not the character sheet one it happens. I'll fix this shortly.

**Comment by Azmoria** [comment]
Should be fixed now

![image](https://github.com/Azmoria/dndbeyonddark/assets/65363489/e8e2d02b-526c-4d5c-9308-ee2a51848446)

**Comment by Laughing-Jackal** [comment]
Sorry it took me a bit to respond.

Looks like it's working great on my end! And no worries about getting to it sooner, in fact thanks for getting to it so quickly!
